# Configuration for Real Robot Operation

policy_node:
  ros__parameters:
    model_path: "placeholder_for_model_path"
    clip_actions: true
    clip_value: 3.0
    target_frame: "base_link"
    state_topic: "/joint_states"
    use_sim_time: false
    normalize_observations: true
    invert_target_pose: false
    use_tf_transform: false
    direct_joint_control: false

controller:
  ros__parameters:
    action_scale: 0.5 
    trajectory_duration: 1.0 
    min_trajectory_duration: 0.5 
    max_velocity: 0.8 
    moving_average: 0.8 
    command_topic: "/joint_trajectory_controller/joint_trajectory"
    state_topic: "/joint_states"
    use_relative_commands: false
    use_sim_time: false
    scale_factor: 0.5  

target_pose_publisher:
  ros__parameters:
    frame_id: "base_link"
    publish_rate: 15.0
    use_sim_time: false

pose_visualizer:
  ros__parameters:
    use_sim_time: false 