# Configuration for Simulation

policy_node:
  ros__parameters:
    model_path: "placeholder_for_model_path"
    clip_actions: true
    clip_value: 3.0
    target_frame: "base_link"
    state_topic: "/joint_states"
    use_sim_time: true
    normalize_observations: true
    invert_target_pose: false
    use_tf_transform: false
    direct_joint_control: false

controller:
  ros__parameters:
    action_scale: 1.0
    trajectory_duration: 0.05
    min_trajectory_duration: 0.2
    max_velocity: 1.0
    moving_average: 0.5
    command_topic: "/joint_trajectory_controller/joint_trajectory"
    state_topic: "/joint_states"
    use_relative_commands: false
    use_sim_time: true

target_pose_publisher:
  ros__parameters:
    frame_id: "base_link"
    publish_rate: 10.0
    use_sim_time: true

pose_visualizer:
  ros__parameters:
    use_sim_time: true 