# Configuration for Simulation

policy_node:
  ros__parameters:
    model_path: "placeholder_for_model_path"  # This will be set in the launch file
    clip_actions: true
    clip_value: 3.0  # Increased to accommodate the larger output range
    target_frame: "base_link"
    state_topic: "/joint_states"
    use_sim_time: true
    # New observation handling options
    normalize_observations: true   # Normalize observations to range [-1, 1]
    invert_target_pose: false      # Try setting to true if target poses seem reversed
    use_tf_transform: false        # Use TF to transform poses if needed
    direct_joint_control: false     # Indicates model outputs direct joint targets, not normalized actions

controller:
  ros__parameters:
    action_scale: 1.0  # Reduced from 3.0 for safer movements
    trajectory_duration: 0.05  # Fast for simulation
    min_trajectory_duration: 0.2
    max_velocity: 1.0
    moving_average: 0.5
    command_topic: "/joint_trajectory_controller/joint_trajectory"
    state_topic: "/joint_states"
    use_relative_commands: false   # Set to false as we'll use direct joint targets
    use_sim_time: true

target_pose_publisher:
  ros__parameters:
    frame_id: "base_link"
    publish_rate: 10.0  # Faster rate for simulation
    use_sim_time: true

pose_visualizer:
  ros__parameters:
    use_sim_time: true 